spring.application.name=smartbank

spring.datasource.url=jdbc:mysql://localhost:3306/smartbank
spring.datasource.username=root
spring.datasource.password=Yagnesh@5657
jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=help.smartbank@gmail.com
spring.mail.password=yylq khfn kqhx judw
razorpay.key.id=rzp_test_SzVDgvTYtwmPE4
razorpay.key.secret=h1hNJPUdm5piEHC3cKfnsog1

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true